# Generated by Django 4.0.3 on 2022-04-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('published_date', models.CharField(max_length=10)),
                ('ISBN_number', models.IntegerField(max_length=13)),
                ('page_count', models.IntegerField()),
                ('preview_link', models.URLField()),
                ('language', models.CharField(max_length=2)),
            ],
        ),
    ]
