# Generated by Django 4.0.3 on 2022-04-12 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_isbn_number_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN_number',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='ISBN number must contain only number!', regex='[0-9]+')]),
        ),
    ]
